[package]
name = "query-engine-wasm"
version = "0.1.0"
edition = "2021"

[lib]
doc = false
crate-type = ["cdylib"]
name = "query_engine_wasm"

[dependencies]
anyhow = "1"
user-facing-errors = { path = "../../libs/user-facing-errors" }
prisma-models = { path = "../prisma-models" }

thiserror = "1"
connection-string = "0.1"
url = "2"
serde_json.workspace = true
serde.workspace = true

wasm-bindgen = { version = "0.2.84" }
tsify = { version = "0.4.3", features = ["js"] }
wasm-bindgen-futures = "0.4.34"
serde-wasm-bindgen = "0.4.5"
js-sys = "0.3.61"

[build-dependencies]
napi-build = "1"
