name: cargo pants

on:
  # push:
    # branches:
      # - main
  #pull_request:
    #paths:
      #- '*Cargo.*' # this makes no sense as dependencies can go bad by itself, not only on updated
  schedule:
    # https://crontab.guru - “At every 15th minute past every hour from 3 through 5.”
    - cron: '28 3 * * *'
  
jobs:
  benchmark:
    name: "Run cargo-pants on Linux"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Install cargo-pants
        run:  cargo install cargo-pants

      - name: Run cargo pants --dev
        run: cargo pants --dev

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: 'cargo pants failed :x:'
          SLACK_COLOR: '#FF0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_WASM_FAILING }}
          SLACK_CHANNEL: tech-rust
