name: cargo pants

on:
  # push:
    # branches:
      # - main
  pull_request:
    paths:
      - '*Cargo.*'

jobs:
  benchmark:
    name: "Run carg-pants on Linux"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Install cargo-pants
        run:  cargo install cargo-pants

      - name: Run cargo pants --dev
        run: cargo pants --dev
